services:
  backend:
    container_name: kkFileView
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8012:8012"
    environment:
      KK_BASE_URL: https://file.xmmzeg.top
    restart: always